### ISSUE TITLE
Does this plugin work with files stored on S3?

### ISSUE THREAD

**Issue by panosdigital** [MDXDave/force-download#1]
I'm trying to use this plugin to force download an image file that is stored on a S3 container but I get an error:

`yii\base\UnknownPropertyException` in `/vendor/yiisoft/yii2/base/Component.php` line 154

```
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: craft\awss3\Volume::path
```

```
throw new UnknownPropertyException('Getting unknown property: ' . get_class($this) . '::' . $name);
```

**Comment by mikefrancis** [comment]
I am having the same error 😕

**Comment by mikefrancis** [comment]
In this file:

https://github.com/MDXDave/force-download/blob/master/src/twigextensions/ForceDownloadTwigExtension.php#L147

If I change:

```php
return $volume->path;
```

to:

```php
return $volume->url;
```

It works. Maybe need something in there to determine if the Asset Volume has URLs?

**Comment by mikefrancis** [comment]
@baronetto I have forked the repo if you want to get this working without having to commit `/vendor`.

Just add:

```
"repositories": [
    {
      "type": "git",
      "url": "https://github.com/mikefrancis/force-download"
    }
  ]
```

to `composer.json` and change the constraints to:

```
"mdxdave/force-download": "dev-master"
```

**Comment by MDXDave** [comment]
Should work in df7245456b415ce13f5ee4e11cbee75e41b48630
